name: ci-planb-karte

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    name: CI Prod
    outputs:
      version: ${{ steps.read_version.outputs.VERSION }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create VERSION file if not exists
        run: |
          if [ ! -f VERSION ]; then
            echo "1.0.0" > VERSION
          fi

      - name: read version file
        id: read_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: bump version
        id: bump
        uses: cbrgm/semver-bump-action@main
        with:
          current-version: ${{steps.read_version.outputs.VERSION}}
          bump-level: patch

      - name: write version file
        run: echo "${{ steps.bump.outputs.new_version }}" > VERSION

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Web image
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: ghcr.io/bcommonslab/planb-karte:latest,ghcr.io/bcommonslab/planb-karte:${{ steps.bump.outputs.new_version }}

      - name: Push version and tag
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add VERSION
          git commit -m "Bump version to ${{ steps.bump.outputs.new_version }} [skip ci]"
          git tag -a -m "${{ steps.bump.outputs.new_version }}" v${{ steps.bump.outputs.new_version }}
          git push --follow-tags
          
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          generate_release_notes: true
          tag_name: v${{ steps.bump.outputs.new_version }}
          
      # Dokploy Deployment - Ersetze YOUR_DEPLOY_KEY durch den tatsächlichen Key
      - name: Trigger deployment
        run: curl -X GET https://dokploy.bcommonslab.org/api/deploy/compose/YOUR_DEPLOY_KEY 